'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
<Assembly: AssemblyVersionAttribute("0.0.0.0"),  _
 Assembly: AssemblyFileVersionAttribute("0.0.0.0"),  _
 Assembly: AssemblyCompanyAttribute("Sevansoft"),  _
 Assembly: AssemblyProductAttribute("Sevansoft.Extensions"),  _
 Assembly: AssemblyCopyrightAttribute("Copyright © 2000-2017 Sevansoft"),  _
 Assembly: AssemblyConfigurationAttribute("RELEASE"),  _
 Assembly: AssemblyInformationalVersionAttribute("0.0")> 

